### ISSUE TITLE
Credits and Licenses

### ISSUE THREAD

**Issue by jpavlich** [epiverse-trace/blueprints#3]
There are two things I would suggest to make explicit in the document:

- It would be a good idea to standardize the way to credit authors of code that we reuse. I would suggest to simply add a brief comment --just before the line where the reused code was inserted-- saying something like "credits:", "reused from:", or "adapted from:", followed by the url pointing to the original source. That way we can automatically create a document that summarizes all credits to external code

- When reusing external code, ensure that their licenses are compatible with ours. For instance, if we chose MIT or a similar license for our projects, it may not be a good idea to reuse GPL code, since we would be compelled to change our license to GPL, too. I general, I would avoid any code with licenses --either open or non non open source-- that are more restrictive than ours

**Comment by thibautjombart** [comment]
Thanks for this, I think both are very good ideas! I suspect nobody will object, so let's go ahead and add what you suggested.
Would you like to make these changes in a PR? If so, could you make sure to add yourself a in the list of alphabetically sorted contributors?

**Comment by jpavlich** [comment]
@thibautjombart I tried to push the changes into a new branch, but it says that I don't have push permissions. Would you please help me with that?

**Comment by thibautjombart** [comment]
Thanks for flagging this. Now members should have push access on all repos, so you should be good for a PR. This may be good timing though, as I have just made some structural changes: now the document 'blueprints.Rmd' is used to generate blueprints in different formats (md, pdf, html). I am adding automation so that these will be generated automatically when the Rmd is changed. As a consequence, edits should no longer be made to `blueprints.md` but to `blueprints.Rmd`. 

Could you replicate your edits on the Rmd document? Sorry about this, the structure change was bad timing, but better earlier than later.

**Comment by jpavlich** [comment]
No problem, I just did it and created the PR. Who should approve the PR and merge?

**Comment by thibautjombart** [comment]
I'm the maintainer so I'll take care of it for the time being; so far there are no rules for numbers of approvals needed etc. I think we'll make them up organically as we need them. Just made suggestions on the PR. Thanks!

**Comment by thibautjombart** [comment]
Closed via https://github.com/epiverse-trace/blueprints/pull/4 

Thanks!
